### ISSUE TITLE
blogpost date renders wrong

### ISSUE THREAD

**Issue by juliendonck** [monadic-xyz/access-p2p#18]
The date of the blogpost renders wrong. I put in `(2019, 12, 18)` to represent today but it renders as `18 jan 2020` in the html.

**Comment by juliendonck** [comment]
<img width="421" alt="Screenshot 2019-12-18 at 13 36 52" src="https://user-images.githubusercontent.com/2326909/71087118-adef2580-219b-11ea-81d1-8a7a06a307a3.png">

**Comment by xla** [comment]
@juliendonck `Date`s month part is `0` indexed, so you need to do `(2019, 11, 18)`. You can read upon it in the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date).

**Comment by juliendonck** [comment]
lol, so silly. And 2018 then or what?

**Comment by xla** [comment]
@juliendonck For years it's the actual value, unless it's between `0` and `99`.
